### ISSUE TITLE
What would be the names of the market cap object key?

### ISSUE THREAD

**Issue by steviecs** [tiaanduplessis/coinmarketcap-api#10]
I'm building a node.js app that wants to compare the predicted price of a coin against what it's market cap would need to be to achieve that price. Do you have additional object key names for other metrics about that coin's object? Or would they be the same as the actual API?

**Comment by thebenlamm** [comment]
It seems this project returns the raw response from coinmarketcap. Your best bet would be to check out their response object example.

**Comment by tiaanduplessis** [comment]
@thebenlamm is correct. @skramzy please check out [coinmarketcap docs](https://coinmarketcap.com/api/). This library is just a simple wrapper on it.

**Comment by abhinavk99** [comment]
I think this can be closed since there hasn't been any activity for over a year. Feel free to reopen.
