### ISSUE TITLE
How the better way to decode object "quote" ?

### ISSUE THREAD

**Issue by RNOVAKOSKY** [tiaanduplessis/coinmarketcap-api#25]
About, by example...
**client.getQuotes({id: '1'}).then(console.log).catch(console.error)**
give the result as:

{ status:
   { timestamp: '2018-10-09T18:25:52.372Z',
     error_code: 0,
     error_message: null,
     elapsed: 8,
     credit_count: 1 },
  data:
   { '1':
      { id: 1,
        name: 'Bitcoin',
        symbol: 'BTC',
        slug: 'bitcoin',
        circulating_supply: 17313137,
        total_supply: 17313137,
        max_supply: 21000000,
        date_added: '2013-04-28T00:00:00.000Z',
        num_market_pairs: 6293,
        cmc_rank: 1,
        last_updated: '2018-10-09T18:24:28.000Z',
        quote: [Object] } } }

quote isn't decoded, how the better way to show all decoded ?
Sugestion too: these example results can be part of doc manual.

**Comment by abhinavk99** [comment]
It's not that it's not decoded, it's that Javascript's console.log doesn't print out objects inside nested objects to avoid showing too much output. Try the code snippet below to print out both.

```javascript
client.getQuotes({id: '1'})
  .then(info => {
    // Print out the info
    console.log(info);
    // Print out the quote object
    console.log(info.data['1'].quote);
  })
  .catch(console.error);
```

**Comment by kolya182** [comment]
@RNOVAKOSKY Or you can try https://stackoverflow.com/a/38768951/2110448.

**Comment by abhinavk99** [comment]
Closing since the question has been answered.
