### ISSUE TITLE
make a currency chart 

### ISSUE THREAD

**Issue by osafahmad** [tiaanduplessis/coinmarketcap-api#44]
![Screenshot_2019-08-09-14-43-11-73](https://user-images.githubusercontent.com/23560192/62770471-8d5be400-bab4-11e9-9452-35918e60aef1.png)
Hi . i want to know that . what are the object needs to be use for currency chart . Please guide me . Thanks .

**Comment by abhinavk99** [comment]
I'm not sure it's possible. The free CMC api doesn't have history, only current quote.
