### ISSUE TITLE
marketcap.getQuotes return null for percent_change_

### ISSUE THREAD

**Issue by emmtte** [tiaanduplessis/coinmarketcap-api#47]
````
obj = await marketcap.getQuotes( { symbol: symbols, convert: 'EUR'})
````

Worked well until today

But now "percent_change_1h", "percent_change_24h" & "percent_change_7d" returns null

**Comment by abhinavk99** [comment]
That's probably an issue on CoinMarketCap's side then. The API documentation still shows those attributes so I don't think the API endpoint response format changed. Let me know if the issue persists.

**Comment by abhinavk99** [comment]
Closing since it's been months and there doesn't seem to be an issue anymore.
