### ISSUE TITLE
Update library on npm to v3.1.0

### ISSUE THREAD

**Issue by abhinavk99** [tiaanduplessis/coinmarketcap-api#49]
Currently the library is on v3.0.1 on npm but v3.1.0 on Github. @tiaanduplessis Do you mind publishing the new version to npm when you have time?

**Comment by tiaanduplessis** [comment]
Hi @abhinavk99, No problem. Will do it now 👍

**Comment by tiaanduplessis** [comment]
Version released: https://www.npmjs.com/package/coinmarketcap-api/v/3.1.0
