### ISSUE TITLE
nvalid response body at: https://api.coinmarketcap.com//v1/ticker?limit=10 reason: incorrect header check

### ISSUE THREAD

**Issue by ourarash** [tiaanduplessis/coinmarketcap-api#5]
I found that using this wrapper in cordova generates this error:

`nvalid response body at: https://api.coinmarketcap.com//v1/ticker?limit=10 reason: incorrect header check`

I was able to fix it by adding:
`compress: false
`
to this line:

`  return fetch(`${url}${query ? `?${qs.stringify(query)}` : ''}`,{compress: false} ).then(...
`

**Comment by tiaanduplessis** [comment]
@ourarash thanks for the catch. It would be useful to enhance the wrapper to accept additional configuration options for the request. Will look into extending it ASAP

**Comment by tiaanduplessis** [comment]
fetch is now configurable via the constructor since v2.1.0
