### ISSUE TITLE
Why quote data is undefined?

### ISSUE THREAD

**Issue by Vrm4** [tiaanduplessis/coinmarketcap-api#55]
Hi , my issue on the title 

```
import CoinMarketCap from 'coinmarketcap-api'
 
const apiKey = 'my-api-key'
const client = new CoinMarketCap(apiKey)
 
let tryAPI = client.getQuotes({symbol: ['BTC', 'ETH']}).then(data => console.log(data.quote)).catch(console.error)
```
![78h](https://user-images.githubusercontent.com/71084215/124540223-9f249e00-de27-11eb-8298-ae28b3d92a6a.png)

**Comment by abhinavk99** [comment]
Hi, did you put in an api key? You need to get one from the coinmarketcap website and replace where it says 'my-api-key' with your key.

**Comment by Vrm4** [comment]
> Hi, did you put in an api key? You need to get one from the coinmarketcap website and replace where it says 'my-api-key' with your key.

I have a API key , my json data : 
![result](https://user-images.githubusercontent.com/71084215/124555304-9f309800-de3f-11eb-8729-0df9a5267119.png)

**Comment by abhinavk99** [comment]
Console log doesn't print out the entire json, try printing data.BTC.quote or data.ETH.quote

**Comment by Vrm4** [comment]
> Console log doesn't print out the entire json, try printing data.BTC.quote or data.ETH.quote

I need to do data.data, I missed it, thank you very much , it worked

`then(data => console.log(data.data.BTC.quote))`

**Comment by abhinavk99** [comment]
You're welcome
